#ifndef QJULIA_QJULIA2_H_ 
#define QJULIA_QJULIA2_H_ 

#include "core/algorithm.h"
#include "core/arg_parse.h"
#include "core/array2d.h"
#include "core/base.h"
#include "core/camera.h"
#include "core/color.h"
#include "core/developer.h"
#include "core/engine.h"
#include "core/entity.h"
#include "core/film.h"
#include "core/image.h"
#include "core/image_io.h"
#include "core/integrator.h"
#include "core/integrator_return.h"
#include "core/intersection.h"
#include "core/light.h"
#include "core/material.h"
#include "core/object.h"
#include "core/qjs_parser.h"
#include "core/ray.h"
#include "core/scene_builder.h"
#include "core/scene_builder_register.h"
#include "core/scene.h"
#include "core/shape.h"
#include "core/spectrum.h"
#include "core/texture.h"
#include "core/timer.h"
#include "core/transform.h"
#include "core/vector.h"
#include "core/scene.h"
#include "core/world.h"
#include "core/integrator/default.h"

#endif
